version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat-system-db
    environment:
      POSTGRES_DB: chat_system
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: